In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [59]:
df=pd.read_csv('encoding_dataset.csv')

In [60]:
df.isnull().sum()

Customer_ID         0
Customer_Gender     0
Payment_Method      0
Education_Level     0
Customer_Loyalty    0
Purchase_Amount     0
dtype: int64

# In this we are going to use encoding technique to give compare the value of the sstring value because machine does not know how to distinguish bewtween the no. then only know numerical value

1. Encoding (in this we will  give value eq to 1 to that string and then 0 to other )

In [61]:
df.head(10)

Customer_ID Customer_Gender Payment_Method Education_Level Customer_Loyalty  \
0       C5374           Other     Debit Card      Bachelor’s           Silver   
1       C3280            Male           Cash             PhD           Bronze   
2       C3380          Female     Debit Card     High School           Silver   
3       C4447          Female            UPI        Master’s           Silver   
4       C2170          Female     Debit Card        Master’s             Gold   
5       C1174           Other            UPI        Master’s           Silver   
6       C5607           Other            UPI      Bachelor’s             Gold   
7       C5352            Male           Cash             PhD           Bronze   
8       C9108           Other           Cash             PhD           Silver   
9       C8760            Male           Cash             PhD           Bronze   

   Purchase_Amount  
0          3573.85  
1          4279.67  
2           904.41  
3           824.00  
4           310.38  
5          3668.02  
6          3112.43  
7          1478.35  
8          2164.13  
9          1745.86

In [62]:
# first works on customer_gender 
# for that we use preprocessing library and its OneHotEnocoder for  doing this  form sklearn 

In [63]:
from sklearn.preprocessing import OneHotEncoder

In [64]:
Encoder=OneHotEncoder()
encod=Encoder.fit_transform(df[['Customer_Gender']]).toarray()

In [65]:
encod

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1

you can see here taht here female=0 , male=1 and other=2 assigned as per the aplphabetical order 

In [66]:
df[['Customer_Gender']]

Customer_Gender
0            Other
1             Male
2           Female
3           Female
4           Female
..             ...
95            Male
96          Female
97            Male
98            Male
99            Male

[100 rows x 1 columns]

In [67]:
encoder_df=pd.DataFrame(encod, columns=Encoder.get_feature_names_out(['Customer_Gender'] ))

In [68]:
encoder_df

Customer_Gender_Female  Customer_Gender_Male  Customer_Gender_Other
0                      0.0                   0.0                    1.0
1                      0.0                   1.0                    0.0
2                      1.0                   0.0                    0.0
3                      1.0                   0.0                    0.0
4                      1.0                   0.0                    0.0
..                     ...                   ...                    ...
95                     0.0                   1.0                    0.0
96                     1.0                   0.0                    0.0
97                     0.0                   1.0                    0.0
98                     0.0                   1.0                    0.0
99                     0.0                   1.0                    0.0

[100 rows x 3 columns]

# now this is creating the problem of sparx and also for big no. of class (means different categories ) then the no. of attributes will be too much so, to resolve that we will use label encoding 

In [69]:
from sklearn.preprocessing import LabelEncoder

In [70]:
letEncode=LabelEncoder()

In [71]:
labelencoded=letEncode.fit_transform(df[['Payment_Method']])

C:\Users\Acer\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [72]:

len(labelencoded)

100

In [73]:
labelencoded

array([2, 0, 2, 3, 2, 3, 3, 0, 0, 0, 1, 1, 2, 1, 0, 3, 0, 3, 1, 0, 1, 3,
       1, 1, 2, 3, 2, 0, 2, 1, 3, 0, 0, 1, 1, 1, 0, 1, 3, 1, 0, 3, 3, 0,
       1, 0, 0, 2, 0, 3, 3, 0, 1, 3, 3, 3, 3, 1, 2, 3, 0, 1, 3, 2, 2, 3,
       0, 0, 1, 1, 1, 2, 0, 3, 1, 3, 1, 0, 3, 3, 3, 0, 1, 3, 2, 0, 1, 0,
       2, 3, 3, 1, 3, 0, 2, 0, 2, 3, 2, 1])

In [74]:
showlabel=pd.DataFrame(df[['Payment_Method']] , labelencoded)

In [75]:
showlabel

Payment_Method
2      Debit Card
0      Debit Card
2      Debit Card
3             UPI
2      Debit Card
..            ...
0      Debit Card
2      Debit Card
3             UPI
2      Debit Card
1            Cash

[100 rows x 1 columns]

In [76]:
# above is not mapping correctly 

In [77]:
# for correct mapping we will use encoder.classes_ , dict , zip , map

In [81]:
encodermap=dict(zip(letEncode.classes_ , letEncode.transform(letEncode.classes_)))

In [82]:
encodermap

{'Cash': 0, 'Credit Card': 1, 'Debit Card': 2, 'UPI': 3}

In [83]:
df['labelEncoded']=df['Payment_Method'].map(encodermap)

In [85]:
df[['labelEncoded']]

labelEncoded
0              2
1              0
2              2
3              3
4              2
..           ...
95             0
96             2
97             3
98             2
99             1

[100 rows x 1 columns]

In [86]:
# now the problem how to priporty then for that come ordinal Encoding (( in this we will assign value as per the priority order we decide))

In [90]:
from sklearn.preprocessing import OrdinalEncoder

In [91]:
df.head(4)

Customer_ID Customer_Gender Payment_Method Education_Level Customer_Loyalty  \
0       C5374           Other     Debit Card      Bachelor’s           Silver   
1       C3280            Male           Cash             PhD           Bronze   
2       C3380          Female     Debit Card     High School           Silver   
3       C4447          Female            UPI        Master’s           Silver   

   Purchase_Amount  labelEncoded  
0          3573.85             2  
1          4279.67             0  
2           904.41             2  
3           824.00             3

In [94]:
# apply ordinalencoder on education level
df['Education_Level'].unique()

array(['Bachelor’s', 'PhD', 'High School', 'Master’s'], dtype=object)

In [101]:
ordinalencoder=OrdinalEncoder()
orderedlevel = OrdinalEncoder(categories=[["High School", "Bachelor’s", "Master’s", "PhD"]])

encodedpart=orderedlevel.fit_transform(df[['Education_Level']])

In [102]:
encodedpart

array([[1.],
       [3.],
       [0.],
       [2.],
       [2.],
       [2.],
       [1.],
       [3.],
       [3.],
       [3.],
       [0.],
       [0.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.],
       [3.],
       [2.],
       [1.],
       [1.],
       [3.],
       [1.],
       [2.],
       [1.],
       [1.],
       [1.],
       [3.],
       [3.],
       [3.],
       [0.],
       [2.],
       [3.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [3.],
       [1.],
       [3.],
       [0.],
       [0.],
       [0.],
       [1.],
       [3.],
       [1.],
       [2.],
       [2.],
       [0.],
       [3.],
       [3.],
       [1.],
       [1.],
       [2.],
       [3.],
       [1.],
       [2.],
       [1.],
       [1.],
       [0.],
       [1.],
       [2.],
       [3.],
       [1.],
       [2.],
       [0.],
       [0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [3.],
       [1.],
       [3.],
       [3.],

In [104]:
# Ordinal Target Encoding 
mean_price=df.groupby('Education_Level')['Purchase_Amount'].mean()

In [105]:
mean_price

Education_Level
Bachelor’s     2320.623667
High School    2177.040000
Master’s       3320.906522
PhD            2745.314583
Name: Purchase_Amount, dtype: float64

In [106]:
# This give us the mean price on the basis of Education leve

In [108]:
# Ordinal Target Encoding 
mean_price=df.groupby('Education_Level')['Purchase_Amount'].mean().to_dict()

In [109]:
mean_price

{'Bachelor’s': 2320.6236666666664,
 'High School': 2177.04,
 'Master’s': 3320.90652173913,
 'PhD': 2745.3145833333333}